export const testimonials = [
    {
        name: "John Doe",
        position: "CTO || Demo Company",
        image: "https://randomuser.me/api/portraits/men/32.jpg",
        testimonial: "This product is absolutely amazing! The quality is top-notch, and the experience has been seamless. Highly recommend!",
        linkedin: "https://linkedin.com/in/johndoe",
        email: "johndoe@example.com",
    },
    {
        name: "Jane Smith",
        position: "CEO || Tech Innovators",
        image: "https://randomuser.me/api/portraits/women/44.jpg",
        testimonial: "A game-changer! The usability and design are outstanding. I'm very impressed with the results.",
        linkedin: "https://linkedin.com/in/janesmith",
        email: "janesmith@example.com",
    },
    {
        name: "Michael Johnson",
        position: "Lead Engineer || AI Labs",
        image: "https://randomuser.me/api/portraits/men/55.jpg",
        testimonial: "Highly efficient and reliable. This product exceeded my expectations in every aspect!",
        linkedin: "https://linkedin.com/in/michaeljohnson",
        email: "michaeljohnson@example.com",
    },
    {
        name: "Emily White",
        position: "Product Manager || NextGen Tech",
        image: "https://randomuser.me/api/portraits/women/60.jpg",
        testimonial: "An exceptional product that truly delivers on its promises. I love how easy it is to use!",
        linkedin: "https://linkedin.com/in/emilywhite",
        email: "emilywhite@example.com",
    },
    {
        name: "David Brown",
        position: "Freelance Developer",
        image: "https://randomuser.me/api/portraits/men/15.jpg",
        testimonial: "I've tried many similar solutions, but this one stands out due to its quality and performance!",
        linkedin: "https://linkedin.com/in/davidbrown",
        email: "davidbrown@example.com",
    },
    {
        name: "Chris Brown",
        position: "Freelance Developer",
        image: "https://randomuser.me/api/portraits/men/5.jpg",
        testimonial: "The best product I've ever used in this category! Simply outstanding.",
        linkedin: "https://linkedin.com/in/chrisbrown",
        email: "chrisbrown@example.com",
    },
    {
        name: "David Lee",
        position: "Software Engineer",
        image: "https://randomuser.me/api/portraits/men/95.jpg",
        testimonial: "Sleek, efficient, and highly functional. This product is worth every penny!",
        linkedin: "https://linkedin.com/in/davidlee",
        email: "davidlee@example.com",
    },
];