import ForestContainer from "@/components/animations/bg/threejs/forest/ForestContainer";

export const metadata = {
  title: "About || Educations || Muhammad Ashraful Alam",
  description: "Generated by create next app collaborated by github.com/muhamash",
};

export default async function EducationsPage() {
  return (
    <div className="relative">
      <ForestContainer />
      
      <div className="relative z-20">
         <p >hello</p>
      </div>

      
    </div>
  );
}