import dynamic from "next/dynamic";

const InstituteCard = dynamic( () => import( "@/components/about/education/InstituteCard" ) );
const ForestContainer = dynamic( () => import( "@/components/animations/bg/threejs/forest/ForestContainer" ) );

export const metadata = {
  title: "About || Educations || Muhammad Ashraful Alam",
  description: "Generated by create next app collaborated by github.com/muhamash",
};

export default async function EducationsPage ()
{
  const educations = [
    {
      "id": 2,
      "institutionName": "Thakurgaon Govt Boys' High School, Thakurgaon",
      "duration": {
        "start": "January 2010 -",
        "end": "March 2017"
      },
      "department": "Science",
      "result": "GPA: 5.00/5.00",
      "achievements": [
        "Project Champion at 34th National Science and Technology Week-2014",
        "Published articles in the school magazine.",
        "Secured 1st placed several times competitions at Bangla New year",
        "GPA - 5.00 (included govt. scholarship of the board of intermediate and secondary education, Dinajpur)",
        "Participated National High School Programming Contest - 2014 on junior Division"
      ],
      "additionalNotes": "Completed Secondary School Certificate (SSC) with a focus on Basic Science [Physics, Chemistry, Biology, General Mathematics and Higher Mathematics]"
    },
    {
      "id": 1,
      "institutionName": "Institute of Science & Technology, Dhanmondi",
      "duration": {
        "start": "February 2023 -",
        "end": "present"
      },
      "department": "Electronics communication and Engineering",
      "result": "CGPA: 3.00/4.00",
      "achievements": [
        "Earned a Basic three days training Certificate from Create IT Institute by on campus campaigning"
      ],
      "additionalNotes": "Deeply interested in research and development in electronics and communication, digital signal processing etc"
    },
    {
      "id": 10,
      "institutionName": "Cantt. Public School & College, Saidpur Cantonment",
      "duration": {
        "start": "June 2017 -",
        "end": "December 2019"
      },
      "department": "Science",
      "result": "GPA: 4.92/5.00",
      "achievements": [
        "Awarded a scholarship for outstanding academic performance.",
        "Participated various programming contest at college level"
      ],
      "additionalNotes": "Completed Higher Secondary School Certificate (HSC) with a focus on Physics, Chemistry, and Mathematics, Biology"
    }
  ];

  return (
    <div className="relative w-full h-full md:my-20 my-[100px] px-5">
      <ForestContainer />
      
      <div className="relative flex items-center justify-center w-full h-full">
        <div className="relative z-20 p-8 bg-gray-100 backdrop-blur-sm bg-opacity-20  rounded-lg shadow-lg max-w-4xl mx-auto mt-10">
          <h1 className="text-3xl font-bold text-center mb-6 font-arsenal text-violet-700">Education Details</h1>
        
          <div className="space-y-6">
            {
              educations?.map( ( edu ) => (
                <InstituteCard key={ edu?.id } edu={ edu } />
                ))
            }
          </div>
        </div>
      </div>
    </div>
  );
}