import dynamic from "next/dynamic";

export const metadata = {
  title: "About || Experiences || Md Ashraful Alam",
  description: "Generated by create next app collaborated by github.com/muhamash",
};

const States = dynamic( () => import( "@/components/home/clients/States" ) );
const GradContainer = dynamic( () => import( "@/components/animations/gradientText/GradContainer" ) );
const ParticlesContainer = dynamic( () => import( "@/components/animations/bg/particles/ParticlesContainer" ) );
const Company = dynamic( () => import( "@/components/about/experiences/Company" ) );

export default async function ExperiencesPage ()
{
  const companies = [
    {
      name: "XpeedLab",
      role: "Software Engineer Intern",
      duration: "2024 - Present",
      logo: "/logos/xpeedlab.jpg",
      description: "XpeedLab is a leading IT solutions company specializing in SaaS products, AI-based systems, and enterprise software solutions.",
      projects: [
        {
          title: "Swachchhota (স্বচ্ছতা)",
          tech: [ "MERN Stack", "Next.js", "GraphQL", "NextAuth" ],
          details: "Developed a cloud-based anti-corruption platform with secure reporting and case tracking."
        },
        {
          title: "AI-Based ATS System",
          tech: [ "Next.js", "Node.js", "MySQL", "Prisma" ],
          details: "Building an automated cloud-based CV Analysis Applicant Tracking System."
        }
      ]
    },
    {
      name: "DesignLadder",
      role: "Jr Software Developer",
      duration: "2022 - 2024",
      logo: "/logos/designLadder.jpeg",
      description: "DesignLadder is a creative agency providing web solutions, branding, and SaaS product development.",
      projects: [
        {
          title: "Task Management System",
          tech: [ "Next.js", "Node.js", "Prisma", "MySQL" ],
          details: "Built a full-stack task management system with JWT-based authentication and task tracking."
        },
        {
          title: "E-Commerce Platform",
          tech: [ "React.js", "Node.js", "MongoDB" ],
          details: "Developed an e-commerce platform with admin dashboards and product management features."
        }
      ]
    }
  ];
  
  return (
    <div className="bg-gradient backdrop-blur-md min-h-screen sticky top-0 w-full pt-[100px] px-4 md:px-7 -z-20 py-10">
      <div className="absolute -z-50">
        <ParticlesContainer />
      </div>

      <States />

      <div>
        <GradContainer
          showBorder={ true }
          text={ "Companies I have worked with!!" }
          className="px-5 py-2 text-xl md:text-3xl font-arsenal mt-10"
        />

        <div className="mt-10 grid grid-cols-1 md:grid-cols-2 gap-8">
          {
            companies && companies?.map( ( company, index ) => (
              <Company index={index} key={index} company={company}/>
            ))
          }
        </div>
      </div>
    </div>
  );
}
