import Modal from "@/components/common/Modal";
import ProjectDetailsHeader from "@/components/pages/projects/modal/ProjectDetailsHeader";
import ProjectSlider from "@/components/pages/projects/modal/Slider";
import { redirect } from "next/navigation";

// export const metadata = {
//   title: "Muhamash || project view",
//   description: "Generated by create next app collaborated by github.com/muhamash",
// };

const projectImages = [
  {
    id: 1,
    src: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=2070&auto=format&fit=crop",
    alt: "Project Screenshot 1",
  },
  {
    id: 2,
    src: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=2070&auto=format&fit=crop",
    alt: "Project Screenshot 2",
  },
  {
    id: 3,
    src: "https://images.unsplash.com/photo-1522252234503-e356532cafd5?q=80&w=2025&auto=format&fit=crop",
    alt: "Project Screenshot 3",
  },
  {
    id: 4,
    src: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=2072&auto=format&fit=crop",
    alt: "Project Screenshot 4",
  },
];

const projectData = {
  name: "Swachchhota (স্বচ্ছতা)",
  description: "A MERN-based anti-corruption platform for secure reporting, case tracking, and legal assistance.",
  features: [
    "Secure Corruption Reporting",
    "Role-based Dashboard",
    "Case Tracking",
    "Public Forum",
    "Legal Assistance",
  ],
  liveDemo: "https://yourprojectlink.com",
  githubRepo: "https://github.com/yourrepo",
  learnMore: "/projects/swachchhota",
};

export default async function ProjectDetailsPage({ params, searchParams }) {
  
    const getParams = await params;
    const getSearchParams = await searchParams;

    if ( getSearchParams?.page )
    {
    const cleanParams = Object.fromEntries(
      Object.entries(getSearchParams)
        .filter(([key]) => key !== "page")
    );

    const queryString = new URLSearchParams(cleanParams).toString();
    const destination = `/projects/${getParams.id}${queryString ? `?${queryString}` : ""}`;

    redirect(destination);
  }

  return (
    <Modal>
      <div className="bg-gray-200 text-black text-xl h-full w-full flex md:flex-row flex-col items-center justify-center py-5 z-50 justify-between md:gap-20 md:px-20 px-10">
        <div className="w-fit flex flex-col">

          <ProjectDetailsHeader project={ projectData } />

        </div>

        <div className="order-1 lg:order-2 md:w-1/2 h-fit">
          <div className="transform transition-all duration-500 hover:-translate-y-1 hover:shadow-xl rounded-xl overflow-hidden">
            <ProjectSlider images={ projectImages } />
          </div>
        </div>
      </div>
    </Modal>
  );
}