import ProjectDetails from "@/components/pages/home/projects/View";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Muhamash || project view",
  description: "Generated by create next app collaborated by github.com/muhamash",
};

export default async function ProjectDetailsPage({ params, searchParams }) {
  
    const getParams = await params;
    const getSearchParams = await searchParams;

    if ( getSearchParams?.page )
    {
    const cleanParams = Object.fromEntries(
      Object.entries(getSearchParams)
        .filter(([key]) => key !== "page")
    );

    const queryString = new URLSearchParams(cleanParams).toString();
    const destination = `/projects/${getParams.id}${queryString ? `?${queryString}` : ""}`;

    redirect(destination);
  }

  return (
    <div className="bg-gradient-to-br from-slate-800 via-sky-900 via-teal-950 text-black text-xl h-full w-full flex items-center justify-center">

      <ProjectDetails />
    </div>
  );
}