import Footer from "@/components/pages/home/footer/Footer";
import ActiveFilters from "@/components/pages/projects/filterPage/ActiveFilters";
import ProjectHeader from "@/components/pages/projects/ProjectHeader";
import dynamic from "next/dynamic";
import { Suspense } from "react";

export const metadata = {
  title: "Muhamash || Projects",
  description: "Generated by create next app collaborated by github.com/muhamash",
};

const ClientLayout = dynamic( () => import( '@/components/layouts/AboutLayout' ) );
const SectionScrollLayout = dynamic( () => import( '@/components/layouts/SectionScrollLayout' ) );


export default async function ProjectLayout ( { filters, allProjects , modal} )
{
  return (
    <>
      <SectionScrollLayout className="relative flex flex-col items-center justify-center w-full h-full pt-[100px] bg-gradient-to-r from-slate-600 via-slate-600 to-cyan-900 gap-10 overflow-hidden">
        <ProjectHeader />

        <ActiveFilters />
        {/* css circle */ }
        <div className="bg-violet-950 bg-opacity-50 h-[1000px] w-[1000px] rounded-full absolute blur-3xl -top-40 -right-40 z-0 overflow-hidden hover:blur-xl">

        </div>

        <div className={ "flex md:flex-row flex-col justify-center items-start w-full h-full pb-20 md:px-10 px-5 gap-10 z-20" }>
          { filters }
          <Suspense fallback={<p>Reading the connection!!</p>}>
            { allProjects }
          </Suspense>
          {/* {children} */ }
        </div>

        <div className="bg-green-950 bg-opacity-50 h-[1000px] w-[1000px] rounded-full absolute blur-3xl bottom-20 -left-40 z-0 overflow-hidden hover:blur-xl">

        </div>
      
      </SectionScrollLayout>
      {modal}
      <Footer />
    </>
  );
}