import { getAllProjects } from "@/utils/functions/product";
import dynamic from "next/dynamic";
import { redirect } from "next/navigation";
import { Suspense } from "react";

export const metadata = {
  title: "Projects || Muhamash",
  description: "Generated by create next app collaborated by github.com/muhamash",
};

const ProjectsContainer = dynamic(()=> import("@/components/pages/projects/ProjectsContainer"))
const TagBar = dynamic(()=> import("@/components/pages/projects/Tags"))
const AuoraContainer = dynamic( () => import( "@/components/animations/bg/auora/AuoraContainer" ) );
const GradContainer = dynamic( () => import( "@/components/animations/gradientText/GradContainer" ) );

export default async function ProjectsPage ({searchParams})
{
  const getSearchParams = await searchParams;
  const getProjects = getAllProjects( "all", getSearchParams?.page );

  
  if ( !getSearchParams?.page )
  {
    redirect("/projects?page=1");
  }
  // console.log( getSearchParams );

  return (
    <div className="h-full relative top-0 left-0 right-0 z-20 w-full bg-gradient-to-br from-gray-900 via-slate-900 via-cyan-900">
      {/* <AuoraContainer /> */}
      <div className=" relative py-[150px]">
        <GradContainer
          showBorder={ true }
          text={ "See my all works!!" }
          className="px-5 py-2 text-xl md:text-3xl font-arsenal"
        />

        <div className="py-5">
          <TagBar/>
        </div>

        <div className="py-10">
          <Suspense fallback={
            <div>
              <p>loading</p>
            </div>
          }>
            <ProjectsContainer projectPromise={getProjects} />
          </Suspense>
        </div>
      </div>
    </div>
  );
}
