export const metadata = {
  title: "Projects || Muhamash",
  description: "Generated by create next app collaborated by github.com/muhamash",
};

export default async function ProjectsPage ()
{
  return (
    <div className="text-black bg-gray-300">
      projects page
    </div>
  )
}
