import ProjectsContainer from "@/components/pages/projects/ProjectsContainer";
import TagBar from "@/components/pages/projects/Tags";
import dynamic from "next/dynamic";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Projects || Muhamash",
  description: "Generated by create next app collaborated by github.com/muhamash",
};

const AuoraContainer = dynamic( () => import( "@/components/animations/bg/auora/AuoraContainer" ) );
const GradContainer = dynamic( () => import( "@/components/animations/gradientText/GradContainer" ) );

const items = [
  {
    image: '/ss/hotel.png',
    tags:["node", "nest", "next"],
    link: 'https://muhamash-portfolio.vercel.app/projects',
    title: 'Booking hub',
    description: 'Typescript, MERN, Tailwindcss'
  },
  {
    image: '/ss/movie.png',
    tags:["node", "nest", "tailwind"],
    link: 'https://muhamash-portfolio.vercel.app/projects',
    title: 'MovieDb',
    description: 'Javascript, MERN, Tailwindcss'
  },
  {
    image: '/ss/portfolio.png',
    tags:["react", "nest", "tailwind"],
    link: 'https://muhamash-portfolio.vercel.app/projects',
    title: 'Portfolio',
    description: 'Javascript, MERN, Tailwindcss'
  },
  {
    image: '/ss/task.png',
    tags:["react", "next", "tailwind"],
    link: 'https://muhamash-portfolio.vercel.app/projects',
    title: 'Tasks',
    description: 'Javascript, Mysql, MERN, Prisma'
  },
  {
    image: '/ss/web.png',
    tags:["react", "mysql"],
    link: 'https://muhamash-portfolio.vercel.app/projects',
    title: 'Web',
    description: 'Javascript, MERN, Tailwindcss'
  },
  {
    image: '/ss/web.png',
    tags:["react", "mongodb"],
    link: 'https://muhamash-portfolio.vercel.app/projects',
    title: 'Web',
    description: 'Javascript, MERN, Tailwindcss'
  },
  {
    image: '/ss/hotel.png',
    tags:["react","postgres" ],
    link: 'https://muhamash-portfolio.vercel.app/projects',
    title: 'Web',
    description: 'Javascript, MERN, Tailwindcss'
  }
];

export default async function ProjectsPage ({searchParams})
{
  const getSearchParams = await searchParams;
  
  if ( !getSearchParams?.page )
  {
    redirect("/projects?page=1");
  }
  // console.log( getSearchParams );

  return (
    <div className="h-full relative top-0 left-0 right-0 z-20 w-full bg-gradient-to-br from-gray-700 via-sky-950 via-cyan-900">
      {/* <AuoraContainer /> */}
      <div className=" relative py-[150px]">
        <GradContainer
          showBorder={ true }
          text={ "See my all works!!" }
          className="px-5 py-2 text-xl md:text-3xl font-arsenal"
        />

        <div className="py-5">
          <TagBar/>
        </div>
        <div className="py-10">
          <ProjectsContainer data={ items } />
        </div>

      </div>
    </div>
  );
}
