import dynamic from "next/dynamic";

export const metadata = {
  title: "About || Skills || Md Ashraful Alam",
  description: "Generated by create next app collaborated by github.com/muhamash",
};

const WaterConatainer = dynamic( () => import( "@/components/animations/bg/threejs/water/water/water/WaterConatainer" ) );

export default async function SkillsPage() {
  return (
    <div className="relative w-screen h-screen">
     
      <WaterConatainer />
      
    </div>
  )
}
