import dynamic from "next/dynamic";

export const metadata = {
  title: "About || Skills || Md Ashraful Alam",
  description: "Generated by create next app collaborated by github.com/muhamash",
};

const TextContainerBlackHole =dynamic(()=> import("@/components/animations/bg/threejs/text/TextContainerBlackHole"))
const ParticlesContainer = dynamic( () => import( "@/components/animations/bg/particles/ParticlesContainer" ) );

export default async function SkillsPage() {
  return (
    <div className="relative w-screen h-full">
     
      <div className="absolute -z-50 top-0 w-screen h-screen">
        <ParticlesContainer />
      </div>
      {/* <TextContainerBlackHole/> */}


    </div>
  )
}
