
export const metadata = {
  title: "About || Skills || Md Ashraful Alam",
  description: "Generated by create next app collaborated by github.com/muhamash",
};

export default async function SkillsPage() {
  return (
    <div className="relative">
     
      
    </div>
  )
}
