import { arsenalSC, codeFont, eduFont, nunito, outfit } from "@/components/fonts/fonts";
import Nav from "@/components/nav/Nav";
import "./globals.css";


export const metadata = {
  title: "Muhammad Ashraful Alam",
  description: "Generated by create next app collaborated by github.com/muhamash",
};

// console.log( arsenal_SC, codeFont, eduFont, nunito, outfit );

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="modal-root"
        className={`${arsenalSC.variable} ${nunito.variable} ${outfit.variable} ${eduFont.variable} ${codeFont.variable}  antialiased bg-black overflow-x-hidden`}
      >
        <Nav/>
        { children }
        {/* <Footer/> */}
      </body>
    </html>
  );
}
