import { arsenal_SC, codeFont, eduFont, nunito, outfit } from "@/components/fonts/fonts";
import Nav from "@/components/nav/Nav";
import "./globals.css";


export const metadata = {
  title: "Muhammad Ashraful Alam",
  description: "Generated by create next app collaborated by github.com/muhamash",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${arsenal_SC.className} ${nunito.className} ${outfit.className} ${eduFont.className} ${codeFont.className}  antialiased bg-black overflow-x-hidden min-w-screen min-h-screen`}
      >
        <Nav/>
        { children }
        {/* <Footer/> */}
      </body>
    </html>
  );
}
