import Nav from "@/components/nav/Nav";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Muhammad Ashraful Alam",
  description: "Generated by create next app collaborated by github.com/muhamash",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black overflow-x-hidden min-w-screen min-h-screen`}
      >
        <Nav/>
        { children }
        {/* <Footer/> */}
      </body>
    </html>
  );
}
