import WaterConatainer from "@/components/animations/bg/threejs/water/water/water/WaterConatainer";

export const metadata = {
  title: "About || Achievements || Muhammad Ashraful Alam",
  description: "Generated by create next app collaborated by github.com/muhamash",
};

export default  async function AchievementPage() {
  return (
    <div className="relative">
      {/* <StarConatiner/> */ }
      <WaterConatainer />
      
    </div>
  )
}
