import dynamic from "next/dynamic";

const WaterConatainer = dynamic( () => import( "@/components/animations/bg/threejs/water/water/water/WaterConatainer" ) );

export const metadata = {
  title: "About || Achievements || Muhammad Ashraful Alam",
  description: "Generated by create next app collaborated by github.com/muhamash",
};

export default  async function AchievementPage() {
  return (
    <div className="relative w-screen h-screen flex items-center justify-center">
      {/* <StarConatiner/> */ }
      {/* <WaterConatainer /> */ }
      {/* <AnimatedRadialBackground/> */ }
      {/* <HorizontalScrollWithColors/> */ }
      {/* <VerticalImageLoop/> */}
      {/* <App/> */}
      
      <div className="bg-slate-500 opacity-70 backdrop-blur-md p-10 rounded-md shadow-md font-nunito text-2xl text-violet-300">
        <p>This section is under construction!!!</p>

      </div>
    </div>
  )
}
