import StarConatiner from "@/components/animations/bg/threejs/stars/StarConatiner";

export const metadata = {
  title: "About || Achievements || Muhammad Ashraful Alam",
  description: "Generated by create next app collaborated by github.com/muhamash",
};

export default  async function AchievementPage() {
  return (
    <div className="relative">
      <StarConatiner/>
    </div>
  )
}
